### ISSUE TITLE
Bug - wrapping divETH tries to wrap more than user has?

### ISSUE THREAD

**Issue by yorickdowne** [shamirlabs/diva-alpha-net#10] opened 2023-08-12 07:14 UTC
Probably a bug. I tried to wrap 32 divETH, set a custom allowance for exactly 32 divETH, and it failed with "transfer amount exceeds allowance". Odd.

https://goerli.etherscan.io/tx/0xb4a9c4f44d63187dbe916429165d7880008ea899d4f547abdacd8accf7d7efdc

**Comment by yorickdowne** [comment] 2023-08-12 07:30
OK maybe it doesn't actually try to wrap the right token? Or the allowance is for the wrong one? I tried for 31 divETH wrapped with allowance 32 and this also fails

https://goerli.etherscan.io/tx/0x9cd067015299e5855781aea15255213ea38c04044d047c2cd1ebfd3700f5115b

**Comment by fernantho** [comment] 2023-08-12 18:05
Thanks @yorickdowne!
The problem is that the front-end is pointing to an old wdiveth contract. It is fixed now

**Closed by fernantho** 2023-08-12 18:05 UTC
